name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use your preferred Node version

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Start the server (if applicable)
        run: npm start &
        env:
          DB_HOST: ${{ secrets.DATABASE_HOST }}
          DB_PORT: ${{ secrets.DATABASE_PORT }}
          DB_DATABASE: ${{ secrets.DATABASE_DATABASE }}
          DB_USER: ${{ secrets.DATABASE_USER }}
          DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      - name: Wait for server to be ready
        run: sleep 10
        
      - name: Check server health
        run: curl http://localhost:3000

      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          # Define the Render API endpoint and service ID
          SERVICE_ID=srv-cstlgkdds78s73ckmjcg # Replace this with your actual Service ID
          RENDER_API_URL="https://api.render.com/v1/services/srv-cstlgkdds78s73ckmjcg/deploys"
          # Trigger the deployment using Render's API
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            $RENDER_API_URL